name: release & publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [ "3.10" ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Install changelog generator
        run: |
          pip install github-changelog-generator

      - name: Generate changelog
        run: |
          github_changelog_generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} --token ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the package
        run: poetry build

      - name: Create Draft GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*.whl
          draft: true  # Set to true to make it a draft release
          prerelease: false
          body_path: CHANGELOG.md  # Automatically include changelog

      - name: Publish to PyPI (Only after review)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          verify_metadata: true
